version: '2'
services:
  pypi:
    build: .
    environment:
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      # STORAGE must be s3 or file
      STORAGE: file
      # In case STORAGE=s3, you need to setup following environment
      AWS_ACCESS_KEY_ID: my_aws_access_key
      AWS_SECRET_ACCESS_KEY: my_aws_secret_access_key
      S3_BUCKET: my_bucket
      # Turn off session secure in case don't have ssl.
      # Value = "true" / "false" (must have quote)
      SESSION_SECURE: "false"
    ports:
      - 7001:80


#export ENV=prod
#export AWS_ACCESS_KEY_ID=abc
#export AWS_SECRET_ACCESS_KEY=def
#export ADMIN_USERNAME=admin
#export ADMIN_PASSWORD=admin
#export S3_BUCKET=my_s3_bucket
